name: Publish site

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 17 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate build info
        run: |
          echo "commit: ${{ github.sha }}" > ./_data/buildinfo.yml
          echo "build_id: ${{ github.run_id }}" >> ./_data/buildinfo.yml
          curl -o _data/ejnet.json https://www.edwardjensen.net/feed.json
          curl -o _data/github.json https://api.github.com/users/edwardjensen/repos
          curl -o _data/microphotos.json https://micro.edwardjensen.net/photos/index.json

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '23.6.0'
          cache: 'npm'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          npm ci --omit=dev
      
      - name: Build site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-build
          path: ./_site
  
  deploy-github-pages:
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: Download built Jekyll site
        uses: actions/download-artifact@v4
        with:
          name: jekyll-build
          path: ./_site
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: edwardjensen.github.io
          commit_message: "Build ${{ github.run_id }}"
  
  deploy-cloudflare:
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: Download built Jekyll site
        uses: actions/download-artifact@v4
        with:
          name: jekyll-build
          path: ./_site

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./_site --project-name=${{ secrets.PAGES_PROJECT_NAME }}
