name: Publish landing page on push or nightly at 0900 UTC

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: write

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate build info
        run: |
          echo "commit: ${{ github.sha }}" > ./_data/buildinfo.yml
          echo "build_id: ${{ github.run_id }}" >> ./_data/buildinfo.yml
          echo "build_type: special" >> ./_data/buildinfo.yml
          curl -o _data/ejnet.json https://www.edwardjensen.net/feed.json
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: '3.3.5'
            bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '22.9.0'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          npm ci
      - name: Build site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: edwardjensen.github.io
          commit_message: "Build ${{ github.run_id }}"